# Generated by Django 3.0.5 on 2022-08-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='answer_link',
        ),
        migrations.AddField(
            model_name='vivaresult',
            name='answer_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
